version: '3.7'

services:
  api:
    restart: always
    container_name: trabalho_api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 3002
    ports:
      - 3002:3002
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - postgres
  postgres:
    container_name: trabalho_bd
    image: postgres:13-alpine
    networks:
      - backend
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - api_db_data:/var/lib/postgresql/data
networks:
  backend:
volumes:
  api_db_data:
